version: '3.7'

volumes:
  pg_data:
  static:
  media:
  frontend_build:


services:

  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}

  backend:
    image: airsofter/foodgram_backend
    env_file: .env
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - static:/backend/backend_static/
      - media:/backend/backend_media/
    depends_on:
      - db

  frontend:
    image: airsofter/foodgram_frontend
    volumes:
      - frontend_build:/app/result_build/build
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - frontend
      - backend
    env_file:
      - .env
