version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:

  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ../backend:/backend
      - static:/backend/backend_static/
      - media:/backend/backend_media/
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - frontend
      - backend
    env_file:
      - .env
